//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using SaludMovil.Entidades;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SaludMovilContext : DbContext
    {
        public SaludMovilContext()
            : base("name=SaludMovilContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    	public void SyncObjectState(object entity)
        {
                Entry(entity).State = StateHelper.ConvertState(((IObjectState)entity).ObjectState);
        }
    
        public DbSet<Objeto> Objeto { get; set; }
        public DbSet<RoleObjeto> RoleObjeto { get; set; }
        public DbSet<sm_Alarma> sm_Alarma { get; set; }
        public DbSet<sm_Antecedente> sm_Antecedente { get; set; }
        public DbSet<sm_AntecedentePaciente> sm_AntecedentePaciente { get; set; }
        public DbSet<sm_AspectosMonitoreados> sm_AspectosMonitoreados { get; set; }
        public DbSet<sm_Auditoria> sm_Auditoria { get; set; }
        public DbSet<sm_Calendario> sm_Calendario { get; set; }
        public DbSet<sm_Cargo> sm_Cargo { get; set; }
        public DbSet<sm_CentroSalud> sm_CentroSalud { get; set; }
        public DbSet<sm_Ciudad> sm_Ciudad { get; set; }
        public DbSet<sm_DatosTipoCalificacion> sm_DatosTipoCalificacion { get; set; }
        public DbSet<sm_Departamento> sm_Departamento { get; set; }
        public DbSet<sm_Dispositivo> sm_Dispositivo { get; set; }
        public DbSet<sm_Empresa> sm_Empresa { get; set; }
        public DbSet<sm_EncabezadoValoracionRiesgo> sm_EncabezadoValoracionRiesgo { get; set; }
        public DbSet<sm_Encuesta> sm_Encuesta { get; set; }
        public DbSet<sm_Especialidad> sm_Especialidad { get; set; }
        public DbSet<sm_Estado> sm_Estado { get; set; }
        public DbSet<sm_FiltroNotificaciones> sm_FiltroNotificaciones { get; set; }
        public DbSet<sm_Guia> sm_Guia { get; set; }
        public DbSet<sm_GuiaPaciente> sm_GuiaPaciente { get; set; }
        public DbSet<sm_Homologacion> sm_Homologacion { get; set; }
        public DbSet<sm_Imagen> sm_Imagen { get; set; }
        public DbSet<sm_Informacion> sm_Informacion { get; set; }
        public DbSet<sm_LogNotificaciones> sm_LogNotificaciones { get; set; }
        public DbSet<sm_Medicamento> sm_Medicamento { get; set; }
        public DbSet<sm_MedicionRiesgo> sm_MedicionRiesgo { get; set; }
        public DbSet<sm_MedioAtencion> sm_MedioAtencion { get; set; }
        public DbSet<sm_Notificacion> sm_Notificacion { get; set; }
        public DbSet<sm_NotificacionesPush> sm_NotificacionesPush { get; set; }
        public DbSet<sm_Opcion> sm_Opcion { get; set; }
        public DbSet<sm_OpcionPregunta> sm_OpcionPregunta { get; set; }
        public DbSet<sm_OrigenToma> sm_OrigenToma { get; set; }
        public DbSet<sm_Paciente> sm_Paciente { get; set; }
        public DbSet<sm_PacientePersonalMedico> sm_PacientePersonalMedico { get; set; }
        public DbSet<sm_PacientePrograma> sm_PacientePrograma { get; set; }
        public DbSet<sm_Pais> sm_Pais { get; set; }
        public DbSet<sm_Parametro> sm_Parametro { get; set; }
        public DbSet<sm_ParametroReglas> sm_ParametroReglas { get; set; }
        public DbSet<sm_Parentesco> sm_Parentesco { get; set; }
        public DbSet<sm_Persona> sm_Persona { get; set; }
        public DbSet<sm_PersonalMedico> sm_PersonalMedico { get; set; }
        public DbSet<sm_Poblacion> sm_Poblacion { get; set; }
        public DbSet<sm_Pregunta> sm_Pregunta { get; set; }
        public DbSet<sm_Programa> sm_Programa { get; set; }
        public DbSet<sm_ProgramacionEncuestas> sm_ProgramacionEncuestas { get; set; }
        public DbSet<sm_Respuesta> sm_Respuesta { get; set; }
        public DbSet<sm_Riesgo> sm_Riesgo { get; set; }
        public DbSet<sm_Rol> sm_Rol { get; set; }
        public DbSet<sm_RolOpcion> sm_RolOpcion { get; set; }
        public DbSet<sm_Sincronizacion> sm_Sincronizacion { get; set; }
        public DbSet<sm_SincronizacionTomas> sm_SincronizacionTomas { get; set; }
        public DbSet<sm_TipoAlarma> sm_TipoAlarma { get; set; }
        public DbSet<sm_TipoCalificacion> sm_TipoCalificacion { get; set; }
        public DbSet<sm_TipoDispositivo> sm_TipoDispositivo { get; set; }
        public DbSet<sm_TipoEvento> sm_TipoEvento { get; set; }
        public DbSet<sm_TipoGuia> sm_TipoGuia { get; set; }
        public DbSet<sm_TipoGuiaXPrograma> sm_TipoGuiaXPrograma { get; set; }
        public DbSet<sm_TipoIdentificacion> sm_TipoIdentificacion { get; set; }
        public DbSet<sm_TipoIngreso> sm_TipoIngreso { get; set; }
        public DbSet<sm_TipoMedicamento> sm_TipoMedicamento { get; set; }
        public DbSet<sm_TipoPersona> sm_TipoPersona { get; set; }
        public DbSet<sm_TipoPregunta> sm_TipoPregunta { get; set; }
        public DbSet<sm_Usuario> sm_Usuario { get; set; }
        public DbSet<sm_UsuarioRol> sm_UsuarioRol { get; set; }
        public DbSet<sm_VersionTabla> sm_VersionTabla { get; set; }
    }
}
