//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class RoleObjeto : EntityBase
    {
        [DataMember] 
		public int idObjeto { get; set; }
        [DataMember] 
		public int idRole { get; set; }
        [DataMember] 
		public int idTipoPermiso { get; set; }
    }
}
