//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_Alarma : EntityBase
    {
        [DataMember] 
		public int idAlarma { get; set; }
        [DataMember] 
		public string descripcion { get; set; }
        [DataMember] 
		public int idTipoAlarma { get; set; }
        [DataMember] 
		public int idGuia { get; set; }
        [DataMember] 
		public int idEstado { get; set; }
        [DataMember] 
		public int dias { get; set; }
        [DataMember] 
		public Nullable<int> idMedioEnvio { get; set; }
        [DataMember] 
		public System.DateTime createdDate { get; set; }
        [DataMember] 
		public string createdBy { get; set; }
    }
}
