//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_Calendario : EntityBase
    {
        [DataMember] 
		public int idCalendario { get; set; }
        [DataMember] 
		public int idPaciente { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> fechaDesde { get; set; }
        [DataMember] 
		public Nullable<System.TimeSpan> horaDesde { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> fechaHasta { get; set; }
        [DataMember] 
		public Nullable<System.TimeSpan> horaHasta { get; set; }
        [DataMember] 
		public string descripcion { get; set; }
        [DataMember] 
		public int idOrigen { get; set; }
        [DataMember] 
		public int idEstado { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> createdDate { get; set; }
        [DataMember] 
		public string createdBy { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> updatedDate { get; set; }
        [DataMember] 
		public string updatedBy { get; set; }
    }
}
