//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_Encuesta : EntityBase
    {
        public sm_Encuesta()
        {
            this.sm_Pregunta = new HashSet<sm_Pregunta>();
        }
    
        [DataMember] 
		public int idEncuesta { get; set; }
        [DataMember] 
		public string nombreEncuesta { get; set; }
        [DataMember] 
		public string tema { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> fechaInicio { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> fechaFin { get; set; }
    
        public virtual ICollection<sm_Pregunta> sm_Pregunta { get; set; }
    }
}
