//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_Estado : EntityBase
    {
        public sm_Estado()
        {
            this.sm_Programa = new HashSet<sm_Programa>();
            this.sm_Guia = new HashSet<sm_Guia>();
            this.sm_TipoGuia = new HashSet<sm_TipoGuia>();
        }
    
        [DataMember] 
		public int idEstado { get; set; }
        [DataMember] 
		public string nombre { get; set; }
        [DataMember] 
		public string tabla { get; set; }
    
        public virtual ICollection<sm_Programa> sm_Programa { get; set; }
        public virtual ICollection<sm_Guia> sm_Guia { get; set; }
        public virtual ICollection<sm_TipoGuia> sm_TipoGuia { get; set; }
    }
}
