//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_FiltroNotificaciones : EntityBase
    {
        [DataMember] 
		public int id { get; set; }
        [DataMember] 
		public int idTipoIdentificacion { get; set; }
        [DataMember] 
		public string numeroIdentificacion { get; set; }
        [DataMember] 
		public string tipoMonitoreo { get; set; }
        [DataMember] 
		public int periodicidad { get; set; }
        [DataMember] 
		public int activoMonitoreo { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> fechaInicio { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> fechaFin { get; set; }
        [DataMember] 
		public Nullable<int> cantidadTomas { get; set; }
        [DataMember] 
		public string horaInicio { get; set; }
        [DataMember] 
		public Nullable<int> tipoEvento { get; set; }
        [DataMember] 
		public string nombre { get; set; }
        [DataMember] 
		public string descripcion { get; set; }
        [DataMember] 
		public Nullable<int> idGuiaPaciente { get; set; }
        [DataMember] 
		public Nullable<int> idEstado { get; set; }
    }
}
