//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_Guia : EntityBase
    {
        public sm_Guia()
        {
            this.sm_GuiaPaciente = new HashSet<sm_GuiaPaciente>();
        }
    
        [DataMember] 
		public int idGuia { get; set; }
        [DataMember] 
		public int idTipoGuia { get; set; }
        [DataMember] 
		public string idCodigoTipo { get; set; }
        [DataMember] 
		public string descripcion { get; set; }
        [DataMember] 
		public string version { get; set; }
        [DataMember] 
		public int idPrograma { get; set; }
        [DataMember] 
		public int idRiesgo { get; set; }
        [DataMember] 
		public Nullable<int> cantidadRiesgo { get; set; }
        [DataMember] 
		public System.DateTime createdDate { get; set; }
        [DataMember] 
		public string createdBy { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> updatedDate { get; set; }
        [DataMember] 
		public string updatedBy { get; set; }
        [DataMember] 
		public Nullable<int> idEstado { get; set; }
        [DataMember] 
		public Nullable<int> peso { get; set; }
        [DataMember] 
		public string ce_titulo { get; set; }
        [DataMember] 
		public string ce_url { get; set; }
        [DataMember] 
		public Nullable<int> ce_estadoDoc { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> ce_fechaRegistro { get; set; }
        [DataMember] 
		public Nullable<decimal> po_act { get; set; }
        [DataMember] 
		public Nullable<decimal> po_grupoAct { get; set; }
    
        public virtual sm_Estado sm_Estado { get; set; }
        public virtual sm_Riesgo sm_Riesgo { get; set; }
        public virtual ICollection<sm_GuiaPaciente> sm_GuiaPaciente { get; set; }
        public virtual sm_Programa sm_Programa { get; set; }
        public virtual sm_TipoGuia sm_TipoGuia { get; set; }
    }
}
