//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_GuiaPaciente : EntityBase
    {
        [DataMember] 
		public int idGuiaPaciente { get; set; }
        [DataMember] 
		public int idTipoIdentificacion { get; set; }
        [DataMember] 
		public string numeroIdentificacion { get; set; }
        [DataMember] 
		public int idGuia { get; set; }
        [DataMember] 
		public string observaciones { get; set; }
        [DataMember] 
		public Nullable<int> idEstado { get; set; }
        [DataMember] 
		public Nullable<int> idOrigen { get; set; }
        [DataMember] 
		public Nullable<int> tipoEvento { get; set; }
        [DataMember] 
		public System.DateTime createdDate { get; set; }
        [DataMember] 
		public string createdBy { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> updatedDate { get; set; }
        [DataMember] 
		public string updatedBy { get; set; }
        [DataMember] 
		public string txt1 { get; set; }
        [DataMember] 
		public string txt2 { get; set; }
        [DataMember] 
		public string txt3 { get; set; }
        [DataMember] 
		public string txt4 { get; set; }
        [DataMember] 
		public string txt5 { get; set; }
        [DataMember] 
		public Nullable<decimal> valor1 { get; set; }
        [DataMember] 
		public Nullable<decimal> valor2 { get; set; }
        [DataMember] 
		public Nullable<decimal> valor3 { get; set; }
        [DataMember] 
		public Nullable<decimal> valor4 { get; set; }
        [DataMember] 
		public Nullable<decimal> valor5 { get; set; }
        [DataMember] 
		public string unidad1 { get; set; }
        [DataMember] 
		public string unidad2 { get; set; }
        [DataMember] 
		public string unidad3 { get; set; }
        [DataMember] 
		public string unidad4 { get; set; }
        [DataMember] 
		public string unidad5 { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> fechaEvento { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> fecha1 { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> fecha2 { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> fecha3 { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> fecha4 { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> fecha5 { get; set; }
    
        public virtual sm_Guia sm_Guia { get; set; }
        public virtual sm_OrigenToma sm_OrigenToma { get; set; }
        public virtual sm_Persona sm_Persona { get; set; }
        public virtual sm_TipoEvento sm_TipoEvento { get; set; }
    }
}
