//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_MedicionRiesgo : EntityBase
    {
        [DataMember] 
		public int idMedicionesRiesgo { get; set; }
        [DataMember] 
		public int idTipoMedicion { get; set; }
        [DataMember] 
		public int idPaciente { get; set; }
        [DataMember] 
		public string sexo { get; set; }
        [DataMember] 
		public Nullable<int> edad { get; set; }
        [DataMember] 
		public Nullable<decimal> colesterolTotal { get; set; }
        [DataMember] 
		public Nullable<decimal> colesterolHDL { get; set; }
        [DataMember] 
		public Nullable<decimal> presionSistolica { get; set; }
        [DataMember] 
		public Nullable<bool> esFumador { get; set; }
        [DataMember] 
		public Nullable<bool> diabetes { get; set; }
        [DataMember] 
		public Nullable<decimal> peso { get; set; }
        [DataMember] 
		public Nullable<decimal> talla { get; set; }
        [DataMember] 
		public Nullable<decimal> creatininaSerica { get; set; }
        [DataMember] 
		public Nullable<int> idEstado { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> createdDate { get; set; }
        [DataMember] 
		public string createdBy { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> updatedDate { get; set; }
        [DataMember] 
		public string updatedBy { get; set; }
    }
}
