//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_Notificacion : EntityBase
    {
        [DataMember] 
		public int idNotificacion { get; set; }
        [DataMember] 
		public Nullable<int> idGuia { get; set; }
        [DataMember] 
		public Nullable<int> idUsuario_Solicita { get; set; }
        [DataMember] 
		public Nullable<int> idUsuario_Envia { get; set; }
        [DataMember] 
		public Nullable<int> idUsuario_Destino { get; set; }
        [DataMember] 
		public string asunto { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> fecha_Respuesta { get; set; }
        [DataMember] 
		public Nullable<bool> Resuelto { get; set; }
        [DataMember] 
		public Nullable<bool> Leido { get; set; }
        [DataMember] 
		public string idTipoNotificacion { get; set; }
        [DataMember] 
		public string detalle { get; set; }
        [DataMember] 
		public string idEstado { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> FechaCierre { get; set; }
        [DataMember] 
		public Nullable<int> enviado { get; set; }
    }
}
