//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_Opcion : EntityBase
    {
        public sm_Opcion()
        {
            this.sm_RolOpcion = new HashSet<sm_RolOpcion>();
        }
    
        [DataMember] 
		public int IdOpcion { get; set; }
        [DataMember] 
		public string NombreOpcion { get; set; }
        [DataMember] 
		public string URL { get; set; }
        [DataMember] 
		public int Orden { get; set; }
        [DataMember] 
		public string Descripcion { get; set; }
        [DataMember] 
		public Nullable<int> IdOpcionPadre { get; set; }
        [DataMember] 
		public Nullable<bool> Activa { get; set; }
        [DataMember] 
		public string URLImagen { get; set; }
        [DataMember] 
		public string CreatedBy { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> CreatedDate { get; set; }
        [DataMember] 
		public string UpdatedBy { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<sm_RolOpcion> sm_RolOpcion { get; set; }
    }
}
