//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_Persona : EntityBase
    {
        public sm_Persona()
        {
            this.sm_GuiaPaciente = new HashSet<sm_GuiaPaciente>();
            this.sm_Respuesta = new HashSet<sm_Respuesta>();
        }
    
        [DataMember] 
		public int idTipoIdentificacion { get; set; }
        [DataMember] 
		public string numeroIdentificacion { get; set; }
        [DataMember] 
		public string primerNombre { get; set; }
        [DataMember] 
		public string segundoNombre { get; set; }
        [DataMember] 
		public string primerApellido { get; set; }
        [DataMember] 
		public string segundoApellido { get; set; }
        [DataMember] 
		public int idTipo { get; set; }
        [DataMember] 
		public System.DateTime fechaNacimiento { get; set; }
        [DataMember] 
		public Nullable<int> idCiudad { get; set; }
        [DataMember] 
		public string celular { get; set; }
        [DataMember] 
		public string telefonoFijo { get; set; }
        [DataMember] 
		public string correo { get; set; }
        [DataMember] 
		public System.DateTime createdDate { get; set; }
        [DataMember] 
		public string createdBy { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> updatedDate { get; set; }
        [DataMember] 
		public string updatedBy { get; set; }
    
        public virtual ICollection<sm_GuiaPaciente> sm_GuiaPaciente { get; set; }
        public virtual sm_Paciente sm_Paciente { get; set; }
        public virtual sm_Paciente sm_Paciente1 { get; set; }
        public virtual sm_PacientePrograma sm_PacientePrograma { get; set; }
        public virtual ICollection<sm_Respuesta> sm_Respuesta { get; set; }
    }
}
