//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_ProgramacionEncuestas : EntityBase
    {
        [DataMember] 
		public int idEncuesta { get; set; }
        [DataMember] 
		public string numeroIdentificacion { get; set; }
        [DataMember] 
		public int idTipoIdentificacion { get; set; }
        [DataMember] 
		public string estadoEncuesta { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> fechaEstado { get; set; }
        [DataMember] 
		public Nullable<int> programaAsignado { get; set; }
        [DataMember] 
		public int idProgramacion { get; set; }
    }
}
