//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_Pais : EntityBase
    {
        public sm_Pais()
        {
            this.sm_Departamento = new HashSet<sm_Departamento>();
        }
    
        [DataMember] 
		public int idPais { get; set; }
        [DataMember] 
		public string codigo { get; set; }
        [DataMember] 
		public string nombre { get; set; }
        [DataMember] 
		public int estado { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> CreatedDate { get; set; }
        [DataMember] 
		public string CreatedBy { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> UpdatedDate { get; set; }
        [DataMember] 
		public string UpdatedBy { get; set; }
    
        public virtual ICollection<sm_Departamento> sm_Departamento { get; set; }
    }
}
