//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_Paciente : EntityBase
    {
        [DataMember] 
		public int idTipoIdentificacion { get; set; }
        [DataMember] 
		public string numeroIdentificacion { get; set; }
        [DataMember] 
		public string segmento { get; set; }
        [DataMember] 
		public string planMp { get; set; }
        [DataMember] 
		public string tipoContrato { get; set; }
        [DataMember] 
		public string nombreColectivo { get; set; }
        [DataMember] 
		public Nullable<int> institucion { get; set; }
        [DataMember] 
		public int idTipoIdentificacionMedico { get; set; }
        [DataMember] 
		public string numeroIdentificacionMedico { get; set; }
        [DataMember] 
		public Nullable<int> recibeNotParentesco { get; set; }
        [DataMember] 
		public string nombresParantesco { get; set; }
        [DataMember] 
		public Nullable<int> idParentesco { get; set; }
        [DataMember] 
		public string celularParentesco { get; set; }
        [DataMember] 
		public string telefonoFijoParentesco { get; set; }
        [DataMember] 
		public string correoParentesco { get; set; }
        [DataMember] 
		public Nullable<int> idTipoIngreso { get; set; }
        [DataMember] 
		public Nullable<int> idMedioAtencion { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> fechaRegistro { get; set; }
        [DataMember] 
		public int riesgo { get; set; }
        [DataMember] 
		public int idEstado { get; set; }
        [DataMember] 
		public Nullable<bool> esMonitoreado { get; set; }
        [DataMember] 
		public System.DateTime createdDate { get; set; }
        [DataMember] 
		public string createdBy { get; set; }
        [DataMember] 
		public string updatedBy { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> updatedDate { get; set; }
    
        public virtual sm_CentroSalud sm_CentroSalud { get; set; }
        public virtual sm_MedioAtencion sm_MedioAtencion { get; set; }
        public virtual sm_Parentesco sm_Parentesco { get; set; }
        public virtual sm_Persona sm_Persona { get; set; }
        public virtual sm_Persona sm_Persona1 { get; set; }
        public virtual sm_Riesgo sm_Riesgo { get; set; }
        public virtual sm_TipoIngreso sm_TipoIngreso { get; set; }
    }
}
