//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_Poblacion : EntityBase
    {
        public sm_Poblacion()
        {
            this.sm_Programa = new HashSet<sm_Programa>();
        }
    
        [DataMember] 
		public int idPoblacion { get; set; }
        [DataMember] 
		public string descripcion { get; set; }
        [DataMember] 
		public int idEstado { get; set; }
        [DataMember] 
		public string createdBy { get; set; }
        [DataMember] 
		public System.DateTime createdDate { get; set; }
        [DataMember] 
		public string updatedBy { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> updatedDate { get; set; }
    
        public virtual ICollection<sm_Programa> sm_Programa { get; set; }
    }
}
