//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_Pregunta : EntityBase
    {
        public sm_Pregunta()
        {
            this.sm_OpcionPregunta = new HashSet<sm_OpcionPregunta>();
            this.sm_Respuesta = new HashSet<sm_Respuesta>();
        }
    
        [DataMember] 
		public int idPregunta { get; set; }
        [DataMember] 
		public string nombrePregunta { get; set; }
        [DataMember] 
		public int idTipoPregunta { get; set; }
        [DataMember] 
		public int idEncuesta { get; set; }
        [DataMember] 
		public bool esObligatoria { get; set; }
        [DataMember] 
		public Nullable<int> idOpcionDepende { get; set; }
        [DataMember] 
		public string createdBy { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> createdDate { get; set; }
        [DataMember] 
		public string updatedBy { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> updatedDate { get; set; }
        [DataMember] 
		public int ordenPregunta { get; set; }
    
        public virtual sm_Encuesta sm_Encuesta { get; set; }
        public virtual ICollection<sm_OpcionPregunta> sm_OpcionPregunta { get; set; }
        public virtual sm_TipoPregunta sm_TipoPregunta { get; set; }
        public virtual ICollection<sm_Respuesta> sm_Respuesta { get; set; }
    }
}
