//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_Respuesta : EntityBase
    {
        [DataMember] 
		public int idRespuesta { get; set; }
        [DataMember] 
		public int idPregunta { get; set; }
        [DataMember] 
		public string numeroIdentificacion { get; set; }
        [DataMember] 
		public Nullable<int> idOpcion { get; set; }
        [DataMember] 
		public string respuestaTexto { get; set; }
        [DataMember] 
		public Nullable<float> respuestaNumero { get; set; }
        [DataMember] 
		public Nullable<bool> respuestaSiNo { get; set; }
        [DataMember] 
		public int idTipoIdentificacion { get; set; }
    
        public virtual sm_OpcionPregunta sm_OpcionPregunta { get; set; }
        public virtual sm_Persona sm_Persona { get; set; }
        public virtual sm_Pregunta sm_Pregunta { get; set; }
    }
}
