//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_Riesgo : EntityBase
    {
        public sm_Riesgo()
        {
            this.sm_Guia = new HashSet<sm_Guia>();
            this.sm_Paciente = new HashSet<sm_Paciente>();
        }
    
        [DataMember] 
		public int idRiesgo { get; set; }
        [DataMember] 
		public string nombre { get; set; }
        [DataMember] 
		public int idEstado { get; set; }
        [DataMember] 
		public System.DateTime createdDate { get; set; }
        [DataMember] 
		public string createdBy { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> updatedDate { get; set; }
        [DataMember] 
		public string updatedBy { get; set; }
    
        public virtual ICollection<sm_Guia> sm_Guia { get; set; }
        public virtual ICollection<sm_Paciente> sm_Paciente { get; set; }
    }
}
