//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_Rol : EntityBase
    {
        public sm_Rol()
        {
            this.sm_RolOpcion = new HashSet<sm_RolOpcion>();
            this.sm_UsuarioRol = new HashSet<sm_UsuarioRol>();
        }
    
        [DataMember] 
		public int idRol { get; set; }
        [DataMember] 
		public string nombre { get; set; }
        [DataMember] 
		public bool soloConsulta { get; set; }
        [DataMember] 
		public string createdBy { get; set; }
        [DataMember] 
		public System.DateTime createdDate { get; set; }
        [DataMember] 
		public string updatedBy { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> updatedDate { get; set; }
    
        public virtual ICollection<sm_RolOpcion> sm_RolOpcion { get; set; }
        public virtual ICollection<sm_UsuarioRol> sm_UsuarioRol { get; set; }
    }
}
