//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_Sincronizacion : EntityBase
    {
        [DataMember] 
		public int idVersion { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> fechaCambio { get; set; }
        [DataMember] 
		public string tipoCambio { get; set; }
        [DataMember] 
		public string total_Parcial { get; set; }
        [DataMember] 
		public string mandatoria { get; set; }
        [DataMember] 
		public string instruccion { get; set; }
        [DataMember] 
		public string origen { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> createdDate { get; set; }
        [DataMember] 
		public string createdBy { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> updatedDate { get; set; }
        [DataMember] 
		public string updatedBy { get; set; }
    }
}
