//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_TipoCalificacion : EntityBase
    {
        public sm_TipoCalificacion()
        {
            this.sm_DatosTipoCalificacion = new HashSet<sm_DatosTipoCalificacion>();
        }
    
        [DataMember] 
		public int idTipoCalificacion { get; set; }
        [DataMember] 
		public string descripcion { get; set; }
        [DataMember] 
		public Nullable<int> idEstado { get; set; }
    
        public virtual ICollection<sm_DatosTipoCalificacion> sm_DatosTipoCalificacion { get; set; }
    }
}
