//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_TipoGuiaXPrograma : EntityBase
    {
        [DataMember] 
		public int idPrograma { get; set; }
        [DataMember] 
		public int idTipoGuia { get; set; }
        [DataMember] 
		public Nullable<bool> esPonderadoPorGrupo { get; set; }
        [DataMember] 
		public Nullable<decimal> ponderadorGrupo { get; set; }
    
        public virtual sm_Programa sm_Programa { get; set; }
        public virtual sm_TipoGuia sm_TipoGuia { get; set; }
    }
}
