//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludMovil.Entidades
{
    using System.Runtime.Serialization; 
	using System;
    using System.Collections.Generic;
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class sm_Usuario : EntityBase
    {
        [DataMember] 
		public int idUsuario { get; set; }
        [DataMember] 
		public Nullable<int> idTipoIdentificacion { get; set; }
        [DataMember] 
		public string numeroIdentificacion { get; set; }
        [DataMember] 
		public string usuario { get; set; }
        [DataMember] 
		public string contrasena { get; set; }
        [DataMember] 
		public bool estado { get; set; }
        [DataMember] 
		public Nullable<int> intentos { get; set; }
        [DataMember] 
		public Nullable<int> idEmpresa { get; set; }
        [DataMember] 
		public string createdBy { get; set; }
        [DataMember] 
		public System.DateTime createdDate { get; set; }
        [DataMember] 
		public string updatedBy { get; set; }
        [DataMember] 
		public Nullable<System.DateTime> updatedDate { get; set; }
    }
}
