CREATE TABLE [dbo].[sm_GuiaPaciente] (
    [idGuiaPaciente]       INT             IDENTITY (1, 1) NOT NULL,
    [idTipoIdentificacion] INT             NOT NULL,
    [numeroIdentificacion] NVARCHAR (50)   NOT NULL,
    [idGuia]               INT             NOT NULL,
    [observaciones]        NVARCHAR (256)  NULL,
    [idEstado]             INT             NULL,
    [idOrigen]             INT             NULL,
    [tipoEvento]           INT             NULL,
    [createdDate]          DATETIME        NOT NULL,
    [createdBy]            NVARCHAR (50)   NOT NULL,
    [updatedDate]          DATETIME        NULL,
    [updatedBy]            NVARCHAR (50)   NULL,
    [txt1]                 NVARCHAR (256)  NULL,
    [txt2]                 NVARCHAR (256)  NULL,
    [txt3]                 NVARCHAR (256)  NULL,
    [txt4]                 NVARCHAR (256)  NULL,
    [txt5]                 NVARCHAR (256)  NULL,
    [valor1]               DECIMAL (18, 2) NULL,
    [valor2]               DECIMAL (18, 2) NULL,
    [valor3]               DECIMAL (18, 2) NULL,
    [valor4]               DECIMAL (18, 2) NULL,
    [valor5]               DECIMAL (18, 2) NULL,
    [unidad1]              NVARCHAR (50)   NULL,
    [unidad2]              NVARCHAR (50)   NULL,
    [unidad3]              NVARCHAR (50)   NULL,
    [unidad4]              NVARCHAR (50)   NULL,
    [unidad5]              NVARCHAR (50)   NULL,
    [fechaEvento]          DATETIME        NULL,
    CONSTRAINT [PK_sm_GuiaxPaciente] PRIMARY KEY CLUSTERED ([idGuiaPaciente] ASC),
    CONSTRAINT [FK_sm_GuiaPaciente_sm_OrigenToma] FOREIGN KEY ([idOrigen]) REFERENCES [dbo].[sm_OrigenToma] ([idOrigenToma]),
    CONSTRAINT [FK_sm_GuiaPaciente_sm_Persona] FOREIGN KEY ([idTipoIdentificacion], [numeroIdentificacion]) REFERENCES [dbo].[sm_Persona] ([idTipoIdentificacion], [numeroIdentificacion]),
    CONSTRAINT [FK_sm_GuiaPaciente_sm_TipoEvento] FOREIGN KEY ([tipoEvento]) REFERENCES [dbo].[sm_TipoEvento] ([idTipoEvento]),
    CONSTRAINT [FK_sm_GuiaxPaciente_sm_Guias] FOREIGN KEY ([idGuia]) REFERENCES [dbo].[sm_Guia] ([idGuia])
);

