CREATE TABLE [dbo].[sm_Paciente] (
    [idTipoIdentificacion]       INT            NOT NULL,
    [numeroIdentificacion]       NVARCHAR (50)  NOT NULL,
    [segmento]                   NVARCHAR (50)  NULL,
    [planMp]                     NVARCHAR (50)  NULL,
    [tipoContrato]               NVARCHAR (50)  NULL,
    [nombreColectivo]            NVARCHAR (50)  NULL,
    [institucion]                INT            NULL,
    [idTipoIdentificacionMedico] INT            NOT NULL,
    [numeroIdentificacionMedico] NVARCHAR (50)  NOT NULL,
    [recibeNotParentesco]        INT            NULL,
    [nombresParantesco]          NVARCHAR (150) NULL,
    [idParentesco]               INT            NULL,
    [celularParentesco]          NVARCHAR (50)  NULL,
    [telefonoFijoParentesco]     NVARCHAR (50)  NULL,
    [correoParentesco]           NVARCHAR (50)  NULL,
    [idTipoIngreso]              INT            NULL,
    [idMedioAtencion]            INT            NULL,
    [fechaRegistro]              DATETIME       NULL,
    [riesgo]                     INT            NOT NULL,
    [idEstado]                   INT            NOT NULL,
    [createdDate]                DATETIME       NOT NULL,
    [createdBy]                  NVARCHAR (50)  NOT NULL,
    [updatedBy]                  NVARCHAR (50)  NULL,
    [updatedDate]                DATETIME       NULL,
    CONSTRAINT [PK_sm_Paciente] PRIMARY KEY CLUSTERED ([idTipoIdentificacion] ASC, [numeroIdentificacion] ASC),
    CONSTRAINT [FK_sm_Paciente_sm_CentroSalud] FOREIGN KEY ([institucion]) REFERENCES [dbo].[sm_CentroSalud] ([idCentroSalud]),
    CONSTRAINT [FK_sm_Paciente_sm_MedicoTratante] FOREIGN KEY ([idTipoIdentificacionMedico], [numeroIdentificacionMedico]) REFERENCES [dbo].[sm_Persona] ([idTipoIdentificacion], [numeroIdentificacion]),
    CONSTRAINT [FK_sm_Paciente_sm_MedioAtencion] FOREIGN KEY ([idMedioAtencion]) REFERENCES [dbo].[sm_MedioAtencion] ([idMedioAtencion]),
    CONSTRAINT [FK_sm_Paciente_sm_Parentesco] FOREIGN KEY ([idParentesco]) REFERENCES [dbo].[sm_Parentesco] ([idParentesco]),
    CONSTRAINT [FK_sm_Paciente_sm_Persona] FOREIGN KEY ([idTipoIdentificacion], [numeroIdentificacion]) REFERENCES [dbo].[sm_Persona] ([idTipoIdentificacion], [numeroIdentificacion]),
    CONSTRAINT [FK_sm_Paciente_sm_Riesgo] FOREIGN KEY ([riesgo]) REFERENCES [dbo].[sm_Riesgo] ([idRiesgo]),
    CONSTRAINT [FK_sm_Paciente_sm_TipoIngreso] FOREIGN KEY ([idTipoIngreso]) REFERENCES [dbo].[sm_TipoIngreso] ([idTipoIngreso])
);

